---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: orders-internal
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: orders-internal@sha256:8e0f3b939bd0176c32532e01a7b2f14d7d62b44e7c601543cda6b92fb0afddba
        namespace: evals25-tutoria-cce2
      name: latest
