apiVersion: v1
kind: Template
metadata:
  name: rhmi-lab-internal-camel-api
  displayName: RHMI Lab Fuse Internal API
  annotations:
    displayName: RHMI Lab Fuse Internal API
    description: "The internal Fuse Orders API that's used in RHMI Solution Patterns"
    iconClass: "icon-jboss"
    tags: "fuse,camel,rhmi"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhmi-lab-internal-fuse-api
    name: rhmi-lab-internal-fuse-api
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhmi-lab-internal-fuse-api
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: rhmi-lab-internal-fuse-api
      spec:
        containers:
        - env:
          - name: PG_HOSTNAME
            value: ${PG_HOSTNAME}
          - name: PG_DATABASE
            value: ${PG_DATABASE}
          - name: PG_USERNAME
            value: ${PG_USERNAME}
          - name: PG_PASSWORD
            value: ${PG_PASSWORD}
        image: quay.io/evanshortiss/quay.io/evanshortiss/rhmi-lab-internal-fuse-api:latest
        imagePullPolicy: Always
        securityContext:
          privileged: false
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhmi-lab-internal-fuse-api
    name: rhmi-lab-internal-fuse-api
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: rhmi-lab-internal-fuse-api
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhmi-lab-internal-fuse-api
    name: frontend
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: rhmi-lab-internal-fuse-api
parameters:
- description: The hostname of the PostgreSQL instance orders are stored in
  displayName: PostgreSQL Hostname
  required: true
  name: PG_HOSTNAME
- description: The name of the database in the PostgreSQL instance orders are stored in
  displayName: PostgreSQL Database Name
  required: true
  value: orders
  name: PG_DATABASE
- description: The username for logging into the PostgreSQL instance
  displayName: PostgreSQL Username
  required: true
  name: PG_USERNAME
- description: The password for logging into the PostgreSQL instance
  displayName: PostgreSQL Password
  required: true
  name: PG_PASSWORD
